version: '3.9'

services:
  nginx:
    depends_on:
      - fpm
    links:
      - fpm
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../tmp/nginx:/var/log/nginx:rw

  fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    volumes:
      - ./php-fpm/config.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini:ro
      - ../app:/var/www/html:rw
